### ISSUE TITLE
incompatible with sbt 0.13.8

### ISSUE THREAD

**Issue by justjoheinz** [typelevel/sbt-typelevel#6] opened 2015-09-17 21:47 UTC
sbt-typelevel : 0.3.1
sbt.version: 0.13.8

```
> checkDependencies
[info] Updating {file:/Users/markusklink/Projects/scala/play-spray2json/}play-spray2json...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[trace] Stack trace suppressed: run last compile:ivyReport for the full output.
[error] (compile:ivyReport) java.lang.IllegalStateException: sbt-dependency-graph plugin currently only supports InlineConfiguration of ivy settings (the default in sbt)
```

Downgrading to 0.13.7 solves the problem. This is probably due to https://github.com/jrudolph/sbt-dependency-graph/issues/67

**Comment by larsrh** [comment] 2016-04-10 19:48
Duplicate of #7.

**Closed by larsrh** 2016-04-10 19:48 UTC
